"""first

Revision ID: 7704d7b79101
Revises: 
Create Date: 2024-01-23 23:27:29.303951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7704d7b79101'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('nok_phone_number', sa.String(length=32), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('is_quit', sa.Boolean(), nullable=True),
    sa.Column('is_stop', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.Enum('UNDEFINED', 'MATH', 'ENGLISH', name='subject'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('subject', sa.Enum('UNDEFINED', 'MATH', 'ENGLISH', name='subject'), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('register_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('registers')
    op.drop_table('classes')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
